package ilia.nemankov.model;

public enum HotelType {

    APARTMENT, HOTEL, GUEST_HOUSES, HOSTEL, BED_AND_BREAKFASTS, HOMESTAYS, CAPSULE_HOUSE, HOLIDAY_HOMES, LOVE_HOTELS, VILLAS, CAMPSITES, MOTELS, BOATS, COUNTRY_HOUSES, CHALETS, ECONOMY_HOTELS

}
