CREATE TYPE HOTEL_TYPE AS ENUM ('APARTMENT', 'HOTEL', 'GUEST_HOUSES', 'HOSTEL', 'BED_AND_BREAKFASTS', 'HOMESTAYS', 'CAPSULE_HOUSES', 'HOLIDAY_HOMES', 'LOVE_HOTELS', 'VILLAS', 'CAMPSITES', 'MOTELS', 'BOATS', 'COUNTRY_HOUSES', 'CHALETS', 'ECONOMY_HOTELS');

CREATE TYPE FOOD AS ENUM ('SELF_CATERING', 'BREAKFAST', 'THREE_MEALS', 'ALL_INCLUSIVE', 'BREAKFAST_AND_DINNER');

CREATE TABLE DIRECTION
(
    ID   SERIAL        PRIMARY KEY,
    NAME VARCHAR(256)  UNIQUE NOT NULL
);

CREATE TABLE HOTEL
(
    ID          SERIAL       PRIMARY KEY,
    DIRECTION   INTEGER       REFERENCES DIRECTION (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    ADDRESS     VARCHAR(256) NOT NULL,
	HOTEL_TYPE  HOTEL_TYPE   NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE ROOMS
(
    ID            SERIAL       PRIMARY KEY,
    HOTEL         INTEGER      REFERENCES HOTEL (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    NAME          VARCHAR(128) NOT NULL,
    AREA          INTEGER      NOT NULL,
	ROOMS_NUMBER  INTEGER      CHECK (ROOMS_NUMBER > 0) NOT NULL
);

CREATE TABLE CONFIGURATION
(
    ID            SERIAL       PRIMARY KEY,
    ROOMS         INTEGER      REFERENCES ROOMS (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    CAPACITY      INTEGER      CHECK (CAPACITY > 0) NOT NULL,
	FOOD          FOOD,
	PRICE         INTEGER      CHECK (PRICE > 0) NOT NULL
);

CREATE TABLE RESERVATION
(
    ID             SERIAL       PRIMARY KEY,
	HOTEL          INTEGER      REFERENCES HOTEL (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	NAME           VARCHAR(256) NOT NULL,
	SURNAME        VARCHAR(256) NOT NULL,
	EMAIL          VARCHAR(256) NOT NULL,
	ARRIVAL_DATE   DATE         NOT NULL,
	DEPARTURE_DATE DATE         NOT NULL
);

CREATE TABLE RESERVATED_ROOMS
(
    ID            SERIAL  PRIMARY KEY,
	RESERVATION   INTEGER REFERENCES RESERVATION (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ROOMS         INTEGER REFERENCES ROOMS (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	CONFIGURATION INTEGER REFERENCES CONFIGURATION (ID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	ROOMS_NUMBER  INTEGER CHECK (ROOMS_NUMBER > 0) NOT NULL
);

CREATE INDEX HOTEL_INDEX_DIRECTION ON HOTEL USING HASH(DIRECTION);
CREATE INDEX ROOMS_INDEX_HOTEL ON ROOMS USING HASH(HOTEL);
CREATE INDEX CONFIGURATION_INDEX_ROOMS ON CONFIGURATION USING HASH(ROOMS);
CREATE INDEX RESERVATION_INDEX_HOTEL ON RESERVATION USING HASH(HOTEL);
CREATE INDEX RESERVATED_ROOMS_INDEX_RESERVATION ON RESERVATED_ROOMS USING HASH(RESERVATION);