DROP TABLE RESERVATED_ROOMS;
DROP TABLE RESERVATION;
DROP TABLE CONFIGURATION;
DROP TABLE ROOMS;
DROP TABLE HOTEL;
DROP TABLE CITY;
DROP TABLE COUNTRY;
DROP TYPE  FOOD CASCADE;
DROP TYPE  HOTEL_TYPE CASCADE;